name: pop_scope_aware_cupertino_route
description: an adjustment of the cupertino page transition to be usable with pop scope
version: 0.0.1
homepage: https://github.com/Menelphor

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
